### ISSUE TITLE
git setup with / without composer?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#109]
From [Slack](https://typo3.slack.com/archives/C028JEPJL/p1547213959123400): There was a problem with setting up the commit hooks with composer

```
composer run gerrit:setup
Class TYPO3\CMS\Composer\Scripts\InstallerScripts is not autoloadable, can not call gerrit:setup:commitMessageHook:enable script
Class TYPO3\CMS\Composer\Scripts\InstallerScripts is not autoloadable, can not call gerrit:setup:preCommitHook:enable script
```
Should we still list the copy commands (as before)?

**Comment by sypets** [comment]
See also pending patch for git setup script: https://review.typo3.org/c/59173/

**Comment by maddy2101** [comment]
I dislike composer scripts in general and try to avoid their usage for personal reasons. So all in for re-adding the pure commands to the documentation.
Having several options available is fine with me, too. Just don't make people use any arbitrary scripts for no other reason than 'well, we can'.

**Comment by sypets** [comment]
@maddy2101 please see updated page: https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Setup/Git/Index.html#install-your-commit-hooks

**Comment by maddy2101** [comment]
very good, thank you. Please keep it this way.

Then I guess the issue can be closed?
