### ISSUE TITLE
Proposal: Add HowTo add Backend tranlation

### ISSUE THREAD

**Issue by zdreicom** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#124]

**Comment by sypets** [comment]
Can you add a little more information what you think should be added to the Contribution Guide for this? Thanks.

**Comment by susannemoog** [comment]
No feedback to this issue since 2 years and it's not really clear what kind of translation is meant, I'm going to close this issue now - please open a new issue with additional information if you still think there is something missing.
