### ISSUE TITLE
Add DDEV video to "Setting up TYPO3 with DDEV"

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#141]
There is a video showing installation with DDEV.
https://www.youtube.com/watch?v=HZVMPoI9SIk

It would be very nice to have the video incorporated in this page:
https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Appendix/SettingUpTypo3Ddev.html

**Comment by sypets** [comment]
@tmotyl Generally, we encourage embedding YouTube videos if there is a good one and it is up to date.

Do you want to make the change?

See https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/YoutubeVideos.html for embedding YouTube videos.
