### ISSUE TITLE
Add section about writing and running Javascript tests

### ISSUE THREAD

**Issue by susannemoog** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#159]
A section about the JavaScript / TypeScript setup is missing - should also contain information about how to run the tests / build.

todos:

* [x] Add information about location of TypeScript / SCSS files : in Build/....
* [x] add information about building JavaScript / CSS files (refer to runTests.sh: buildCss, buildJavascript)
* [x] add information about checking / testing TypScript / JavaScript / SCSS: refer to runTests.sh: lintTypescript, lintScss

**Comment by sypets** [comment]
@susannemoog  I added some todos to your issue. Please check if ok this way. Will be working on this.
