### ISSUE TITLE
Git for Windows is outdated

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#228]
* https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Appendix/Windows/GitForWindows.html
* https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/blob/master/Documentation/Appendix/Windows/GitForWindows.rst

----

Please make **general decision first** about the page: If it is necessary, makes sense, will be kept maintained etc. ...

Please feel free to leave comment. **Contributions welcome!**

see also older issue #111 and comment there.

----

There are some things that are outdated.

But preferably check first

* if page is helpful / necessary: should be updated
* if we can **remove** and point to [Git Setup](https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Setup/Git/Index.html) and **not repeat the same commands here too**  That _might_ be the case, if you can use the same or similar commands on Windows / the information is already well documented elsewhere, we could link to that.
 
(All content has to be maintained - not always easy to balance the "make it easy and have complete walkthrough on one page" and "not repeat things on several pages").

Current issues:

* [ ] !!! commit hook download from fileadmin: https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Appendix/Windows/GitForWindows.html#commit-hook
* [ ]  several shell examples are not formatted as code block
* [ ] have to check if this makes sense and is up to date in general and recommended procedure
* [ ] [Git setup / installation](https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Appendix/Windows/GitForWindows.html#installation) with various screenshots - this is prone to change and would have to be checked regularly and is not TYPO3 specific at all?

If possible, we should not re-repeat the Git commands in too many places. The main place for that is the setup.  (**Update**: this depends: It is often more user-friendly to have it all on one page, but not so great to maintain.)

The rest of the things, I can't say because I never work with windows. I would recommend to use a shell which is "bash-similar" (which apparently does exist) and use the same commands as described in [Git Setup](https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Setup/Git/Index.html).

**Comment by liayn** [comment]
First note from my side:
We can skip the whole putty stuff. Windows 10 has ssh and git-bash has ssh-agent.
You can use the usual .ssh/config stuff on Windows just like in Unix.

**Comment by sypets** [comment]
@liayn I would suggest a complete rewrite then. Would you be willing to do that?. 

If not, I would remove the page (or keep placeholder referring to general Git section). 

I will also ask in documentation channel if someone would like to maintain information for Windows in Contrib Guide in general. That would be very welcome!

We should also check the other Windows pages in the Appendix: https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Appendix/Windows/Index.html

Reasoning: There was already an issue from _Jan 15, 2019_ (#111) which I overlooked when I created this one. The issue and the problems (outdated) existed for quite a while. It does not look like anyone looked at this page or at least they did not complain. And that is not a good sign, that the page is actually being used or is useful.

The information about the git hook 

> curl -o .git/hooks/commit-msg "https://typo3.org/fileadmin/resources/git/commit-msg.txt" && chmod +x .git/hooks/commit-msg

https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Appendix/Windows/GitForWindows.html#commit-hook


is definitely very outdated, that is one of the first [patches](https://review.typo3.org/c/Packages/TYPO3.CMS/+/55974) I did in the core, moving that to the git repo in January 2018 and the file was removed: https://typo3.org/fileadmin/resources/git/commit-msg.txt"

This should have gotten noticed and did not.

**Comment by liayn** [comment]
Yes, I will try to rewrite this based on current tools we use on Windows. (less than ever, luckily)

**Comment by liayn** [comment]
Just an update from my side: I didn't forget about this task.

**Comment by sypets** [comment]
@liayn that is great. 

My preference would be to have as little Windows-specific as necessary. If the general workflow can be used for Windows as well - maybe we do not need that much Windows-specific documentation here. So maybe for example, how people work with Git on Windows is a little out of scope here. While I would like to make it as easy as possible for everyone, the documentation needs to be maintained long-term. It has already become apparent that this is a bit difficult to do - if not so many developers use Windows.

**Comment by liayn** [comment]
This can be vastly streamlined. basically all you need is git-for-windows, everything else is shipped with Windows nowadays.

**Comment by liayn** [comment]
@sypets Alright, here is my first attempt. I did not render it locally, so it might not be perfect yet. But I kindly ask for a first review from you, thanks.

**Comment by sypets** [comment]
Fixed with https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/pull/238
