### ISSUE TITLE
Is COMPOSER_ROOT_VERSION still necessary / recommended?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#254]
From current docs:

> Composer cannot detect the TYPO3 version of your cloned project because there is none. Before you run composer install you need to export the [COMPOSER_ROOT_VERSION environment variable](https://getcomposer.org/doc/03-cli.md#composer-root-version). Here you need to set a full version string matching the TYPO3 version of your clone.

> Example:

```
# cd <cloned project>
export COMPOSER_ROOT_VERSION=12.0.0

```
https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Setup/SetupTypo3.html

* I can't find this anywhere in the git repo, not in the Build directory except for:

**Build/gitlab-ci.yml:**

```
variables:
# When a branch derives from main or 10.4 or something, composer stumbles
# if the repos has been 'shallow cloned', can't determine the source branch
# and fails with package conflicts. Having a full clone by setting depth 0
# prevents this, so we don't need to fiddle with COMPOSER_ROOT_VERSION env var.
GIT_DEPTH: 0

```
* search in Slack typo3-cms-coredev latest hit is 2021

see https://getcomposer.org/doc/03-cli.md#composer-root-version

**Comment by mbrodala** [comment]
By now it should be fine to drop this since all packages required as dependency and maintained by TYPO3 also allow `dev-main` (default branch). However, if you work on a different branch (`11.5`, `10.4`, etc.) this may still be necessary.
