### ISSUE TITLE
Undocumented how to handle the limit on characters per line for commit messages in default environment

### ISSUE THREAD

**Issue by rr-it** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#305]
For new contributors following every documented step how to contribute, it is a real hassle to count the characters per line in commit messages.

We do document how to use git.
Nano is the default git editor.
After following all documentation, this setting to show the character limit per line in nano is the only undocumented step I needed to create perfect commit messages.

**Comment by DavidBruchmann** [comment]
According to the discussion on #304 I close this issue too.

**Comment by sypets** [comment]
It has already been closed but maybe some additional considerations: 

While it does seem helpful, info like this must be maintained long term

* there are 2 line limits - one in the subject, one in the body. A line limit in in the editor obscures this fact
* if the line limits are changed in the future, they must be changed in several places (if the limit is added in a code snippet example)
* nano may not be the default editor. More contributors may be using Mac OSX. Seems like vim is the default there. (Personally, I work on Linux and always change it to vim)
* there are some edge cases where the information is not TYPO3 specific but may be helpful

**Comment by rr-it** [comment]
The line limit is not fixed in any way with the `nano` parameter `constantshow`. It's about 'constantly displaying the cursor position in the status bar' and thereby the need to manually count the characters in each line is obsolete.
