### ISSUE TITLE
Optimize order of related chapters

### ISSUE THREAD

**Issue by michadu** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#38]
In the Contribution Guide there is a chapter “Setting up your frontend build toolchain” that assume an already installed source that is described at a later point.
Maybe split the chapter “Prerequisites and useful tools” into “Prerequisites” and “Useful tools” and then put “Setting up your Git environment” between “Prerequisites” and “Useful tools”.

**Comment by sypets** [comment]
I seperated the installation of yarn, composer etc (in section **Setup/Prerequisites**) and the execution of commands which actually require a TYPO3 repository (Setup/SetupTypo3) in my PR: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/pull/43

Can you check if this adresses your issue sufficiently enough and is better now?

**Comment by sypets** [comment]
@michadu I think this is not sufficiently addressed in https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Setup/Index.html

You can do one step after the other. If you disagree or find something else that needs to be fixed, please reopen or add a new issue. Thanks for your input.
