### ISSUE TITLE
Add information about .editorconfig 

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#52]

**Comment by marble** [comment]
I've just added a sample .editorconfig to this page: https://docs.typo3.org/typo3cms/HowToDocument/Incoming/FormattingRestSourceFiles.html

What do you think?

**Comment by sypets** [comment]
A default .editorconfig is already in the core. Maybe we can also refer to that?

https://github.com/TYPO3/TYPO3.CMS/blob/master/.editorconfig

However, you've added more to the rst section. Should we get that patched in the core?

**Comment by marble** [comment]
No, actually it is TAKEN and in sync with that core version of .editorconfig. The difference: I'm setting `root=false`, so our settings don't replace everything people may have set already. And we only add those filetypes we care about. To make that work I had to add the general settings (from that core .editorconfig version) to the specific filetypes.

And new is filetype `*.rst.txt`. I just verified once more: In PhpStorm you can define that type as well and it gets recognized: 
![image](https://user-images.githubusercontent.com/307057/39171175-41810806-479e-11e8-8e8c-0f945ce65e87.png)

So: To me this version seems fine. Unless somebody reports something differen.
