### ISSUE TITLE
Contrib Guide: Migrate things from TYPO3 wiki

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#58]
When moving please make sure to always:
* add a link to new content
* always add `{{delete}}` and `{{outdated}}`

Later (or where it is a no-brainer and it is certain it can be deleted, this can be done right away):

* request a redirect
* delete page

see for information about migrating: https://wiki.typo3.org/WikiMigration

**Important: Some of the pages in the Wiki still contain useful information that is not yet documented in the Contribution Guide. Do not just delete the Wiki pages! Read them carefully and check if there is still text that is worth saving and migrating to the current contribution guide on docs.typo3.org!**

### git:

- [x] https://wiki.typo3.org/Clone_(Git)
- [x] https://wiki.typo3.org/Commit_(Git)
- [x] https://wiki.typo3.org/Commit_Amend_(Git)
- [x] https://wiki.typo3.org/TroubleShooting_(Git) (see [Troubleshooting](https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/Troubleshooting/Index.html) in Contribution Guide)
- [x] https://wiki.typo3.org/CommitMessage_Format_(Git)
- [x] https://wiki.typo3.org/Index_(Git)
- [x] https://wiki.typo3.org/Introduction_(Git)
- [x] https://wiki.typo3.org/Merge_Repositories
- [x] https://wiki.typo3.org/Push_(Git)
- [x] https://wiki.typo3.org/Repository_(Git) 
- [x] https://wiki.typo3.org/Tips_and_Tricks_(Git)
- [x] https://wiki.typo3.org/Branch_(Git)
- [x] https://wiki.typo3.org/Da:Clone_(Git)
- [x] https://wiki.typo3.org/Glossary_(Git)
- [x] https://wiki.typo3.org/Multiple_Branch_Setup
- [x] https://wiki.typo3.org/Update_Git_Submodule_Pointer

### gerrit:

- [x] https://wiki.typo3.org/Gerrit_Review_Workflow: the remaining text has been added with PR #168. Page can be redirected and deleted once this is merged. 
- [x] https://wiki.typo3.org/Gerrit
- [x] https://wiki.typo3.org/Change_Request_(Gerrit)
- [x] https://wiki.typo3.org/Submodules_(Git)
- [x] https://wiki.typo3.org/Git_Gerrit

### PhpStorm

- [x] https://wiki.typo3.org/Development/PHPStorm_Settings

### misc:

- [x] https://wiki.typo3.org/Unit_Testing_TYPO3 (moved to "TYPO3 Explained")
- [x] https://wiki.typo3.org/Contribution_Walkthrough_with_CommandLine
- [x] https://wiki.typo3.org/Bugfixing_Team
- [ ] https://wiki.typo3.org/Development/Memos/TranslationHandling
- [ ] https://wiki.typo3.org/Development/Memos/Architectural_Decisions (outdated but basic idea still relevant)
- [ ] https://wiki.typo3.org/Development/Memos/Important_rst-file_prefix

### About releasing a version

- [ ] https://wiki.typo3.org/Development/Memos/Sprint_Release_Workflow (not sure if this should be in "Contribution Guide")

**Comment by sypets** [comment]
Since PR #168 was added, this can now be considered done. :partying_face: :+1:

**Comment by sypets** [comment]
Keep finding more:

* https://wiki.typo3.org/Development/Memos/TranslationHandling

Might already be handled sufficiently with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1094

**Comment by sypets** [comment]
I am pretty sure this is outdated but it might be worth to take another look at how we deal with this problem now:

* https://wiki.typo3.org/Development/Memos/Architectural_Decisions

**Comment by susannemoog** [comment]
I'm going to close this issue in favor of https://github.com/TYPO3-Documentation/T3DocTeam/issues/154 - while I agree that there might be stuff documented here that sounds relevant, I don't think we need to keep content no-one accessed in the last year(s). If the core team wants to further document how decisions are taken, I'm sure they will notify us (or create the PR ;)).

**Comment by sypets** [comment]
Thanks for taking care of it. Looks good and looks like you already made huge progress :thumbsup:
