### ISSUE TITLE
Add information for rendering Changelog

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow#82]

**Comment by marble** [comment]
See https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-RenderTypo3Documentation/issues/2

**Comment by sypets** [comment]
Is done, see https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/BugfixingAZ/Index.html#render-the-changelog
